version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env